version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - default
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=P@ssw0rd
  redis:
    image: redis
    container_name: redisdb
    networks:
      - default
    ports:
      - 6379:6379
  flower:
    image: mher/flower
    container_name: flower
    networks:
      - default
    environment:
      - CELERY_BROKER_URL=amqp://admin:P@ssw0rd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555

# Using default network 
